import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3"
import { PrismaClient } from "prisma/generated/prisma/client"

const adapter = new PrismaBetterSqlite3({ url: process.env.DATABASE_URL || 'file:./prisma/dev.db' })
const prisma = new PrismaClient({ adapter })

async function main() {
  console.log('🌱 Начинаем сидирование базы данных...')

  // Создаем пользователей
  console.log('👥 Создаем пользователей...')
  const users = await Promise.all([
    prisma.user.upsert({
      where: { email: 'alice@prisma.io' },
      update: {},
      create: {
        email: 'alice@prisma.io',
        name: 'Alice',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alice',
        password: '$2b$10$rOyRjZqCJQpKz3j5K8L9HuZ8K9L9L9L9L9L9L9L9L9L9L9L9L9L9O',
        role: 'ADMIN',
        verified: true,
      },
    }),
    prisma.user.upsert({
      where: { email: 'bob@prisma.io' },
      update: {},
      create: {
        email: 'bob@prisma.io',
        name: 'Bob',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bob',
        password: '$2b$10$rOyRjZqCJQpKz3j5K8L9HuZ8K9L9L9L9L9L9L9L9L9L9L9L9L9O',
        role: 'USER',
        verified: true,
      },
    }),
    prisma.user.upsert({
      where: { email: 'charlie@prisma.io' },
      update: {},
      create: {
        email: 'charlie@prisma.io',
        name: 'Charlie',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=charlie',
        password: '$2b$10$rOyRjZqCJQpKz3j5K8L9HuZ8K9L9L9L9L9L9L9L9L9L9L9L9L9O',
        role: 'USER',
        verified: false,
      },
    }),
    prisma.user.upsert({
      where: { email: 'diana@prisma.io' },
      update: {},
      create: {
        email: 'diana@prisma.io',
        name: 'Diana',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=diana',
        password: '$2b$10$rOyRjZqCJQpKz3j5K8L9HuZ8K9L9L9L9L9L9L9L9L9L9L9O',
        role: 'USER',
        verified: true,
      },
    }),
    prisma.user.upsert({
      where: { email: 'eve@prisma.io' },
      update: {},
      create: {
        email: 'eve@prisma.io',
        name: 'Eve',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=eve',
        password: '$2b$10$rOyRjZqCJQpKz3j5K8L9HuZ8K9L9L9L9L9L9L9L9L9L9L9O',
        role: 'USER',
        verified: true,
      },
    }),
  ])

  console.log(`✅ Создано ${users.length} пользователей`)

  // Удаляем существующие скины для чистого сидирования
  await prisma.skin.deleteMany({})

  // Создаем скины CS:GO с реальными изображениями с сайта lis-skins.com
  // Используем ТОЛЬКО market_images (не market_stickers - это стикеры!)
  console.log('🔫 Создаем скины...')
  const skins = [
    // AWP скины
    {
      name: 'AWP | Dragon Lore',
      weapon: 'AWP',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 12000.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/11097_s.png',
      isAvailable: true,
      float: 0.020683,
      isStatTrak: false,
      sellerId: users[0].id,
    },
    {
      name: 'AWP | Gungnir',
      weapon: 'AWP',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 8500.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/145549_s.png',
      isAvailable: true,
      float: 0.057988,
      isStatTrak: false,
      sellerId: users[1].id,
    },
    {
      name: 'AWP | Gungnir',
      weapon: 'AWP',
      itemType: 'SKIN' as const,
      condition: 'MINIMAL_WEAR' as const,
      price: 7200.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/145420_s.png',
      isAvailable: true,
      float: 0.073546,
      isStatTrak: false,
      sellerId: users[2].id,
    },
    {
      name: 'AWP | Asiimov',
      weapon: 'AWP',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 6800.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/11011_s.png',
      isAvailable: true,
      float: 0.012345,
      isStatTrak: false,
      sellerId: users[3].id,
    },
    {
      name: 'AWP | Asiimov',
      weapon: 'AWP',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 7500.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/11011_s.png',
      isAvailable: true,
      float: 0.008765,
      isStatTrak: true,
      sellerId: users[4].id,
    },
    {
      name: 'AWP | Medusa',
      weapon: 'AWP',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 9500.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/11096_s.png',
      isAvailable: true,
      float: 0.015678,
      isStatTrak: false,
      sellerId: users[0].id,
    },
    // AK-47 скины
    {
      name: 'AK-47 | Wild Lotus',
      weapon: 'AK-47',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 4500.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/11022_s.png',
      isAvailable: true,
      float: 0.06711,
      isStatTrak: false,
      sellerId: users[1].id,
    },
    {
      name: 'AK-47 | Wild Lotus',
      weapon: 'AK-47',
      itemType: 'SKIN' as const,
      condition: 'MINIMAL_WEAR' as const,
      price: 3800.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/11022_s.png',
      isAvailable: true,
      float: 0.104198,
      isStatTrak: false,
      sellerId: users[2].id,
    },
    {
      name: 'AK-47 | Fire Serpent',
      weapon: 'AK-47',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 3200.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/11023_s.png',
      isAvailable: true,
      float: 0.023456,
      isStatTrak: false,
      sellerId: users[3].id,
    },
    {
      name: 'AK-47 | Vulcan',
      weapon: 'AK-47',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 1800.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/11024_s.png',
      isAvailable: true,
      float: 0.034567,
      isStatTrak: false,
      sellerId: users[4].id,
    },
    {
      name: 'AK-47 | Redline',
      weapon: 'AK-47',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 450.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/11025_s.png',
      isAvailable: true,
      float: 0.045678,
      isStatTrak: false,
      sellerId: users[0].id,
    },
    {
      name: 'AK-47 | Redline',
      weapon: 'AK-47',
      itemType: 'SKIN' as const,
      condition: 'FIELD_TESTED' as const,
      price: 280.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/11025_s.png',
      isAvailable: true,
      float: 0.245678,
      isStatTrak: false,
      sellerId: users[1].id,
    },
    // M4A4 скины
    {
      name: 'M4A4 | Howl',
      weapon: 'M4A4',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 3200.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/10619_s.png',
      isAvailable: true,
      float: 0.0547,
      isStatTrak: false,
      sellerId: users[2].id,
    },
    {
      name: 'M4A4 | Howl',
      weapon: 'M4A4',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 3800.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/10619_s.png',
      isAvailable: true,
      float: 0.023456,
      isStatTrak: true,
      sellerId: users[3].id,
    },
    {
      name: 'M4A4 | Howl',
      weapon: 'M4A4',
      itemType: 'SKIN' as const,
      condition: 'MINIMAL_WEAR' as const,
      price: 2800.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/10619_s.png',
      isAvailable: true,
      float: 0.104168,
      isStatTrak: true,
      sellerId: users[4].id,
    },
    {
      name: 'M4A4 | Asiimov',
      weapon: 'M4A4',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 550.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/10620_s.png',
      isAvailable: true,
      float: 0.014567,
      isStatTrak: false,
      sellerId: users[0].id,
    },
    {
      name: 'M4A4 | Desolate Space',
      weapon: 'M4A4',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 420.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/10621_s.png',
      isAvailable: true,
      float: 0.025678,
      isStatTrak: false,
      sellerId: users[1].id,
    },
    // M4A1-S скины
    {
      name: 'M4A1-S | Icarus Fell',
      weapon: 'M4A1-S',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 460.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/10607_s.png',
      isAvailable: true,
      float: 0.009876,
      isStatTrak: false,
      sellerId: users[2].id,
    },
    {
      name: 'M4A1-S | Hyper Beast',
      weapon: 'M4A1-S',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 320.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/10608_s.png',
      isAvailable: true,
      float: 0.012345,
      isStatTrak: false,
      sellerId: users[3].id,
    },
    {
      name: 'M4A1-S | Blue Phosphor',
      weapon: 'M4A1-S',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 380.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/10609_s.png',
      isAvailable: true,
      float: 0.018765,
      isStatTrak: true,
      sellerId: users[4].id,
    },
    // Butterfly Knife скины
    {
      name: 'Butterfly Knife | Doppler Ruby',
      weapon: 'Butterfly Knife',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 8500.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/99050_s.png',
      isAvailable: true,
      float: 0.003846,
      isStatTrak: false,
      sellerId: users[0].id,
    },
    {
      name: 'Butterfly Knife | Doppler Ruby',
      weapon: 'Butterfly Knife',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 9200.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/139237_s.png',
      isAvailable: true,
      float: 0.028726,
      isStatTrak: true,
      sellerId: users[1].id,
    },
    {
      name: 'Butterfly Knife | Doppler Ruby',
      weapon: 'Butterfly Knife',
      itemType: 'SKIN' as const,
      condition: 'MINIMAL_WEAR' as const,
      price: 7800.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/144724_s.png',
      isAvailable: true,
      float: 0.074647,
      isStatTrak: false,
      sellerId: users[2].id,
    },
    {
      name: 'Butterfly Knife | Doppler Sapphire',
      weapon: 'Butterfly Knife',
      itemType: 'SKIN' as const,
      condition: 'MINIMAL_WEAR' as const,
      price: 6800.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/145037_s.png',
      isAvailable: true,
      float: 0.079159,
      isStatTrak: true,
      sellerId: users[3].id,
    },
    {
      name: 'Butterfly Knife | Doppler Black Pearl',
      weapon: 'Butterfly Knife',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 7200.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/99065_s.png',
      isAvailable: true,
      float: 0.03381,
      isStatTrak: false,
      sellerId: users[4].id,
    },
    {
      name: 'Butterfly Knife | Gamma Doppler Emerald',
      weapon: 'Butterfly Knife',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 9500.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/151310_s.png',
      isAvailable: true,
      float: 0.031635,
      isStatTrak: false,
      sellerId: users[0].id,
    },
    {
      name: 'Butterfly Knife | Fade',
      weapon: 'Butterfly Knife',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 8800.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/99051_s.png',
      isAvailable: true,
      float: 0.007654,
      isStatTrak: false,
      sellerId: users[1].id,
    },
    {
      name: 'Butterfly Knife | Tiger Tooth',
      weapon: 'Butterfly Knife',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 7500.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/99052_s.png',
      isAvailable: true,
      float: 0.009876,
      isStatTrak: false,
      sellerId: users[2].id,
    },
    // Karambit скины
    {
      name: 'Karambit | Gamma Doppler Emerald',
      weapon: 'Karambit',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 9800.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/98776_s.png',
      isAvailable: true,
      float: 0.029689,
      isStatTrak: false,
      sellerId: users[3].id,
    },
    {
      name: 'Karambit | Gamma Doppler Emerald',
      weapon: 'Karambit',
      itemType: 'SKIN' as const,
      condition: 'MINIMAL_WEAR' as const,
      price: 8800.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/99098_s.png',
      isAvailable: true,
      float: 0.072503,
      isStatTrak: false,
      sellerId: users[4].id,
    },
    {
      name: 'Karambit | Gamma Doppler Emerald',
      weapon: 'Karambit',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 10500.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/139254_s.png',
      isAvailable: true,
      float: 0.027169,
      isStatTrak: true,
      sellerId: users[0].id,
    },
    {
      name: 'Karambit | Doppler Black Pearl',
      weapon: 'Karambit',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 9200.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/98948_s.png',
      isAvailable: true,
      float: 0.019646,
      isStatTrak: false,
      sellerId: users[1].id,
    },
    {
      name: 'Karambit | Fade',
      weapon: 'Karambit',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 9200.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/98949_s.png',
      isAvailable: true,
      float: 0.006789,
      isStatTrak: false,
      sellerId: users[2].id,
    },
    {
      name: 'Karambit | Tiger Tooth',
      weapon: 'Karambit',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 8200.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/98950_s.png',
      isAvailable: true,
      float: 0.008765,
      isStatTrak: false,
      sellerId: users[3].id,
    },
    {
      name: 'Karambit | Doppler Ruby',
      weapon: 'Karambit',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 8800.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/98951_s.png',
      isAvailable: true,
      float: 0.012345,
      isStatTrak: false,
      sellerId: users[4].id,
    },
    // Перчатки
    {
      name: 'Sport Gloves | Pandora\'s Box',
      weapon: 'Sport Gloves',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 5500.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/16599_s.png',
      isAvailable: true,
      float: 0.069916,
      isStatTrak: false,
      sellerId: users[0].id,
    },
    {
      name: 'Sport Gloves | Hedge Maze',
      weapon: 'Sport Gloves',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 4200.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/16512_s.png',
      isAvailable: true,
      float: 0.069921,
      isStatTrak: false,
      sellerId: users[1].id,
    },
    {
      name: 'Sport Gloves | Hedge Maze',
      weapon: 'Sport Gloves',
      itemType: 'SKIN' as const,
      condition: 'MINIMAL_WEAR' as const,
      price: 3800.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/16525_s.png',
      isAvailable: true,
      float: 0.149788,
      isStatTrak: false,
      sellerId: users[2].id,
    },
    {
      name: 'Specialist Gloves | Crimson Kimono',
      weapon: 'Specialist Gloves',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 4800.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/16619_s.png',
      isAvailable: true,
      float: 0.068518,
      isStatTrak: false,
      sellerId: users[3].id,
    },
    {
      name: 'Moto Gloves | Spearmint',
      weapon: 'Moto Gloves',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 3500.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/16883_s.png',
      isAvailable: true,
      float: 0.069987,
      isStatTrak: false,
      sellerId: users[4].id,
    },
    // Glock скины
    {
      name: 'Glock-18 | Fade',
      weapon: 'Glock-18',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 2800.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/10482_s.png',
      isAvailable: true,
      float: 0.001234,
      isStatTrak: false,
      sellerId: users[0].id,
    },
    {
      name: 'Glock-18 | Water Elemental',
      weapon: 'Glock-18',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 35.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/10483_s.png',
      isAvailable: true,
      float: 0.023456,
      isStatTrak: false,
      sellerId: users[1].id,
    },
    {
      name: 'Glock-18 | Neo-Noir',
      weapon: 'Glock-18',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 120.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/10484_s.png',
      isAvailable: true,
      float: 0.014567,
      isStatTrak: false,
      sellerId: users[2].id,
    },
    // USP-S скины
    {
      name: 'USP-S | Kill Confirmed',
      weapon: 'USP-S',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 260.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/10503_s.png',
      isAvailable: true,
      float: 0.015678,
      isStatTrak: false,
      sellerId: users[3].id,
    },
    {
      name: 'USP-S | Kill Confirmed',
      weapon: 'USP-S',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 320.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/10503_s.png',
      isAvailable: true,
      float: 0.008765,
      isStatTrak: true,
      sellerId: users[4].id,
    },
    {
      name: 'USP-S | Orion',
      weapon: 'USP-S',
      itemType: 'SKIN' as const,
      condition: 'MINIMAL_WEAR' as const,
      price: 42.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/10504_s.png',
      isAvailable: true,
      float: 0.087654,
      isStatTrak: false,
      sellerId: users[0].id,
    },
    // Desert Eagle скины
    {
      name: 'Desert Eagle | Blaze',
      weapon: 'Desert Eagle',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 420.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/10515_s.png',
      isAvailable: true,
      float: 0.003456,
      isStatTrak: false,
      sellerId: users[1].id,
    },
    {
      name: 'Desert Eagle | Golden Koi',
      weapon: 'Desert Eagle',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 85.50,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/10516_s.png',
      isAvailable: true,
      float: 0.007865,
      isStatTrak: false,
      sellerId: users[2].id,
    },
    {
      name: 'Desert Eagle | Cobalt Disruption',
      weapon: 'Desert Eagle',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 25.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/10517_s.png',
      isAvailable: true,
      float: 0.012345,
      isStatTrak: false,
      sellerId: users[3].id,
    },
    // P250 скины
    {
      name: 'P250 | Undertow',
      weapon: 'P250',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 19.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/10507_s.png',
      isAvailable: true,
      float: 0.010234,
      isStatTrak: false,
      sellerId: users[4].id,
    },
    {
      name: 'P250 | Asiimov',
      weapon: 'P250',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 45.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/10508_s.png',
      isAvailable: true,
      float: 0.014567,
      isStatTrak: false,
      sellerId: users[0].id,
    },
    // Bayonet скины
    {
      name: 'Bayonet | Fade',
      weapon: 'Bayonet',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 4200.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/11001_s.png',
      isAvailable: true,
      float: 0.007654,
      isStatTrak: false,
      sellerId: users[1].id,
    },
    {
      name: 'Bayonet | Doppler',
      weapon: 'Bayonet',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 3800.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/11002_s.png',
      isAvailable: true,
      float: 0.012345,
      isStatTrak: false,
      sellerId: users[2].id,
    },
    // Gut Knife скины
    {
      name: 'Gut Knife | Fade',
      weapon: 'Gut Knife',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 850.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/11003_s.png',
      isAvailable: true,
      float: 0.008765,
      isStatTrak: false,
      sellerId: users[3].id,
    },
    {
      name: 'Gut Knife | Doppler',
      weapon: 'Gut Knife',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 720.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/11004_s.png',
      isAvailable: true,
      float: 0.014567,
      isStatTrak: false,
      sellerId: users[4].id,
    },
    // Flip Knife скины
    {
      name: 'Flip Knife | Fade',
      weapon: 'Flip Knife',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 1200.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/11005_s.png',
      isAvailable: true,
      float: 0.009876,
      isStatTrak: false,
      sellerId: users[0].id,
    },
    {
      name: 'Flip Knife | Doppler',
      weapon: 'Flip Knife',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 1100.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/11006_s.png',
      isAvailable: true,
      float: 0.012345,
      isStatTrak: false,
      sellerId: users[1].id,
    },
    // Huntsman Knife скины
    {
      name: 'Huntsman Knife | Fade',
      weapon: 'Huntsman Knife',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 2800.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/11007_s.png',
      isAvailable: true,
      float: 0.008765,
      isStatTrak: false,
      sellerId: users[2].id,
    },
    {
      name: 'Huntsman Knife | Doppler',
      weapon: 'Huntsman Knife',
      itemType: 'SKIN' as const,
      condition: 'FACTORY_NEW' as const,
      price: 2500.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/11008_s.png',
      isAvailable: true,
      float: 0.014567,
      isStatTrak: false,
      sellerId: users[3].id,
    },
    // Стикеры (STICKER) - используем market_stickers для изображений
    {
      name: 'iBUYPOWER | Katowice 2014',
      weapon: 'Sticker',
      itemType: 'STICKER' as const,
      condition: null,
      price: 45000.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_stickers/4a925c14357c0030d66d61fa8dee8ae0.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[0].id,
    },
    {
      name: 'Team Dignitas (Holo) | Katowice 2014',
      weapon: 'Sticker',
      itemType: 'STICKER' as const,
      condition: null,
      price: 35000.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_stickers/e8dad82d7fc327bd3276808ef4382ce4.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[1].id,
    },
    {
      name: 'Titan | Katowice 2014',
      weapon: 'Sticker',
      itemType: 'STICKER' as const,
      condition: null,
      price: 28000.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_stickers/f3923cca9ca01a35a9e3d9264691c8e9.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[2].id,
    },
    {
      name: 'LGB eSports | Katowice 2014',
      weapon: 'Sticker',
      itemType: 'STICKER' as const,
      condition: null,
      price: 22000.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_stickers/aa16a15b028cd3437896f20b1a2aec67.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[3].id,
    },
    {
      name: 'Vox Eminor | Katowice 2014',
      weapon: 'Sticker',
      itemType: 'STICKER' as const,
      condition: null,
      price: 18000.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_stickers/477d09c066227be30f305910b5949398.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[4].id,
    },
    {
      name: 'Ninjas in Pyjamas | Katowice 2014',
      weapon: 'Sticker',
      itemType: 'STICKER' as const,
      condition: null,
      price: 15000.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_stickers/3dc63cd4a759f48667d32b17b48b4858.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[0].id,
    },
    {
      name: 'Virtus.Pro | Katowice 2014',
      weapon: 'Sticker',
      itemType: 'STICKER' as const,
      condition: null,
      price: 12000.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_stickers/4a925c14357c0030d66d61fa8dee8ae1.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[1].id,
    },
    {
      name: 'HellRaisers | Katowice 2014',
      weapon: 'Sticker',
      itemType: 'STICKER' as const,
      condition: null,
      price: 10000.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_stickers/4a925c14357c0030d66d61fa8dee8ae2.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[2].id,
    },
    {
      name: 'Fnatic | Katowice 2014',
      weapon: 'Sticker',
      itemType: 'STICKER' as const,
      condition: null,
      price: 8500.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_stickers/4a925c14357c0030d66d61fa8dee8ae3.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[3].id,
    },
    {
      name: 'Cloud9 | Katowice 2014',
      weapon: 'Sticker',
      itemType: 'STICKER' as const,
      condition: null,
      price: 7500.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_stickers/4a925c14357c0030d66d61fa8dee8ae4.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[4].id,
    },
    {
      name: 'FaZe Clan | Katowice 2017',
      weapon: 'Sticker',
      itemType: 'STICKER' as const,
      condition: null,
      price: 320.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_stickers/4a925c14357c0030d66d61fa8dee8ae5.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[0].id,
    },
    {
      name: 'G2 Esports | Katowice 2019',
      weapon: 'Sticker',
      itemType: 'STICKER' as const,
      condition: null,
      price: 180.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_stickers/4a925c14357c0030d66d61fa8dee8ae6.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[1].id,
    },
    {
      name: 'NAVI | Katowice 2022',
      weapon: 'Sticker',
      itemType: 'STICKER' as const,
      condition: null,
      price: 120.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_stickers/4a925c14357c0030d66d61fa8dee8ae7.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[2].id,
    },
    // Кейсы (CASE)
    {
      name: 'Operation Broken Fang Case',
      weapon: 'Case',
      itemType: 'CASE' as const,
      condition: null,
      price: 85.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/12001_s.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[0].id,
    },
    {
      name: 'Revolution Case',
      weapon: 'Case',
      itemType: 'CASE' as const,
      condition: null,
      price: 95.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/12002_s.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[1].id,
    },
    {
      name: 'Recoil Case',
      weapon: 'Case',
      itemType: 'CASE' as const,
      condition: null,
      price: 75.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/12003_s.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[2].id,
    },
    {
      name: 'Dreams & Nightmares Case',
      weapon: 'Case',
      itemType: 'CASE' as const,
      condition: null,
      price: 110.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/12004_s.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[3].id,
    },
    {
      name: 'Kilowatt Case',
      weapon: 'Case',
      itemType: 'CASE' as const,
      condition: null,
      price: 65.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/12005_s.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[4].id,
    },
    {
      name: 'Anubis Collection Package',
      weapon: 'Case',
      itemType: 'CASE' as const,
      condition: null,
      price: 125.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/12006_s.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[0].id,
    },
    {
      name: 'Chroma Case',
      weapon: 'Case',
      itemType: 'CASE' as const,
      condition: null,
      price: 580.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/12007_s.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[1].id,
    },
    {
      name: 'Chroma 2 Case',
      weapon: 'Case',
      itemType: 'CASE' as const,
      condition: null,
      price: 520.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/12008_s.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[2].id,
    },
    {
      name: 'Chroma 3 Case',
      weapon: 'Case',
      itemType: 'CASE' as const,
      condition: null,
      price: 480.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/12009_s.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[3].id,
    },
    {
      name: 'Gamma Case',
      weapon: 'Case',
      itemType: 'CASE' as const,
      condition: null,
      price: 380.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/12010_s.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[4].id,
    },
    {
      name: 'Gamma 2 Case',
      weapon: 'Case',
      itemType: 'CASE' as const,
      condition: null,
      price: 350.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/12011_s.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[0].id,
    },
    {
      name: 'Glove Case',
      weapon: 'Case',
      itemType: 'CASE' as const,
      condition: null,
      price: 280.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/12012_s.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[1].id,
    },
    {
      name: 'Spectrum Case',
      weapon: 'Case',
      itemType: 'CASE' as const,
      condition: null,
      price: 320.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/12013_s.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[2].id,
    },
    {
      name: 'Spectrum 2 Case',
      weapon: 'Case',
      itemType: 'CASE' as const,
      condition: null,
      price: 290.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/12014_s.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[3].id,
    },
    {
      name: 'Operation Riptide Case',
      weapon: 'Case',
      itemType: 'CASE' as const,
      condition: null,
      price: 72.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/12015_s.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[4].id,
    },
    // Агенты (AGENT)
    {
      name: 'Soldier | Phoenix',
      weapon: 'Agent',
      itemType: 'AGENT' as const,
      condition: null,
      price: 450.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/13001_s.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[0].id,
    },
    {
      name: 'Soldier | Phoenix KSK',
      weapon: 'Agent',
      itemType: 'AGENT' as const,
      condition: null,
      price: 520.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/13002_s.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[1].id,
    },
    {
      name: 'Operator | FBI',
      weapon: 'Agent',
      itemType: 'AGENT' as const,
      condition: null,
      price: 380.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/13003_s.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[2].id,
    },
    {
      name: 'Operator | FBI SWAT',
      weapon: 'Agent',
      itemType: 'AGENT' as const,
      condition: null,
      price: 420.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/13004_s.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[3].id,
    },
    {
      name: 'Specialist | FBI',
      weapon: 'Agent',
      itemType: 'AGENT' as const,
      condition: null,
      price: 350.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/13005_s.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[4].id,
    },
    {
      name: 'Elite Crew | SAS',
      weapon: 'Agent',
      itemType: 'AGENT' as const,
      condition: null,
      price: 480.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/13006_s.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[0].id,
    },
    {
      name: 'Soldier | USAF TACP',
      weapon: 'Agent',
      itemType: 'AGENT' as const,
      condition: null,
      price: 390.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/13007_s.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[1].id,
    },
    {
      name: 'Operator | GSG 9',
      weapon: 'Agent',
      itemType: 'AGENT' as const,
      condition: null,
      price: 410.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/13008_s.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[2].id,
    },
    {
      name: 'Specialist | GSG 9',
      weapon: 'Agent',
      itemType: 'AGENT' as const,
      condition: null,
      price: 370.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/13009_s.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[3].id,
    },
    {
      name: 'Soldier | IDF',
      weapon: 'Agent',
      itemType: 'AGENT' as const,
      condition: null,
      price: 440.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/13010_s.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[4].id,
    },
    {
      name: 'Soldier | IDF KSK',
      weapon: 'Agent',
      itemType: 'AGENT' as const,
      condition: null,
      price: 500.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/13011_s.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[0].id,
    },
    {
      name: 'Operator | IDF',
      weapon: 'Agent',
      itemType: 'AGENT' as const,
      condition: null,
      price: 430.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/13012_s.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[1].id,
    },
    {
      name: 'Specialist | IDF',
      weapon: 'Agent',
      itemType: 'AGENT' as const,
      condition: null,
      price: 400.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/13013_s.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[2].id,
    },
    {
      name: 'Soldier | NSWC SEAL',
      weapon: 'Agent',
      itemType: 'AGENT' as const,
      condition: null,
      price: 460.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/13014_s.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[3].id,
    },
    {
      name: 'Operator | NSWC SEAL',
      weapon: 'Agent',
      itemType: 'AGENT' as const,
      condition: null,
      price: 490.00,
      iamgeUrl: 'https://assets.lis-skins.com/market_images/13015_s.png',
      isAvailable: true,
      float: null,
      isStatTrak: false,
      sellerId: users[4].id,
    },
  ]

  // Создаем скины
  const createdSkins = await Promise.all(
    skins.map((skin) =>
      prisma.skin.create({
        data: skin,
      })
    )
  )

  console.log(`✅ Создано ${createdSkins.length} скинов`)

  console.log('🎉 Сидирование завершено успешно!')
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error('❌ Ошибка при сидировании:', e)
    await prisma.$disconnect()
    process.exit(1)
  })
